### ISSUE TITLE
No "Open App" button when opening the Instagram page

### ISSUE THREAD

**Issue by vladko456** [russdreamer/instagram-followers-statistics#20]
No "Open App" button when opening the Instagram page.  I tried reinstalling the script, but it didn't help.

**Comment by fictionalchrctr** [comment]
Same thing. This is because there was an error in developers console.
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' *.facebook.com *.fbcdn.net *.facebook.net 127.0.0.1:* blob: data: 'self' *.teststagram.com *.instagram.com static.cdninstagram.com *.google-analytics.com *.google.com 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash, or a nonce ('nonce-...') is required to enable inline execution.

**Comment by russdreamer** [comment]
@vladko456 @fictionalchrctr 
The issue is fixed in new 5.3 version, please follow the link to update: [new version](https://github.com/russdreamer/instagram-followers-statistics/raw/master/installation.user.js).

please check.

**Comment by gseidler** [comment]
Open button still not showing for me on Safari 17 + Tampermonkey 4.20.6188.

**Comment by russdreamer** [comment]
@gseidler Unfortunately, [Tampermonkey extension itself won't work in Safari ](https://github.com/Tampermonkey/tampermonkey/issues/296#issuecomment-222356524)for such websites as instagram, because such websites enabled CSP.  That might be that other browsers will stop working for CSP enabled websites one day as well.
Currently, there are 2 options: 
1. Use another browser (recommended option)
2. Usie Safari and copy-paste [this script](https://github.com/russdreamer/instagram-followers-statistics/blob/master/console_script_v4.js) directly to Safari console. This link is for the current version only, it might change, please grab the last version [from here](https://github.com/russdreamer/instagram-followers-statistics), see`console_script_v<BIGGEST_VERSION_NUMBER>` (not recommended, as some features might not work properly)
